# Generated by Django 4.1 on 2023-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_validationcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationcode',
            name='send_email_status',
            field=models.IntegerField(choices=[(0, 'unsend'), (1, 'send')], default=0),
        ),
    ]
