# Generated by Django 4.1 on 2023-01-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
