# Generated by Django 4.1 on 2023-01-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_validationcode_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidationCode',
        ),
    ]
