# Generated by Django 4.1 on 2023-01-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='txid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='type',
            field=models.IntegerField(choices=[(1, 'paper'), (2, 'airplane'), (3, 'water'), (4, 'towers'), (5, 'methanol'), (6, 'saving')]),
        ),
    ]
