# Generated by Django 4.1 on 2023-01-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_share_txid_alter_share_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='valid',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'confirmed'), (3, 'not confirmed')]),
        ),
    ]
