# Generated by Django 4.1 on 2023-01-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_share_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='valid',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'confirmed'), (3, 'not confirmed')], default=1),
        ),
    ]
