# Generated by Django 4.1 on 2023-01-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemExceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('login_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کاربری کاربر')),
                ('file_path', models.CharField(blank=True, max_length=250, null=True, verbose_name='مسیر محل قرارگیری کد')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='شماره خط')),
                ('exception_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان خطا')),
                ('exception_content', models.TextField(verbose_name='محتوای خطا')),
                ('exact_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات دقیق خطا')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'لاگ خطای سیستم',
                'verbose_name_plural': 'لاگ خطاهای سیستم',
            },
        ),
    ]
