# Generated by Django 4.1 on 2023-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_ticket_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemexceptions',
            options={'verbose_name': 'error_logs', 'verbose_name_plural': 'error_logs'},
        ),
        migrations.AddField(
            model_name='share',
            name='unconfirmed_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
